version: '3'

services:
  nginx:
    build: 
      context: nginx
    container_name: nginx
    ports: 
      - 8080:80
    networks:
      - nginx-network
    depends_on: 
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    environment: 
      - DB_USERNAME=fullcycle
      - DB_PASSWORD=fullcycle
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=students-db
    networks: 
      - node-network
      - nginx-network 
    volumes: 
      - /usr/src/app/node_modules
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=students-db
      - MYSQL_USER=fullcycle
      - MYSQL_PASSWORD=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge
  nginx-network:
    driver: bridge
